# Generated by Django 3.1.6 on 2021-03-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('apisource', models.CharField(max_length=200)),
                ('resourceurl', models.CharField(max_length=200)),
                ('population', models.BigIntegerField()),
            ],
        ),
    ]
